### ISSUE TITLE
Title text does not display after 'npm build'

### ISSUE THREAD

**Issue by adampwells** [creativetimofficial/ct-vue-now-ui-kit-pro#1]
# Prerequisites 

I recently bought Vue Now UI Kit Pro.

I have run 'npm install' and 'npm run dev' and the presentation page loads like the demo.

When I build the production version 'npm run build' and serve it using 'serve -s dist' the following element just displays a gradient box, without text.

`<h1 data-v-46fc392a="" data-rellax-speed="-2" class="h1-seo">Now UI Kit</h1>`

# Expected Behavior

I expect to see the text "Now UI Kit" when serving the dist folder and browsing the presentation.
The text is visible with 'npm run dev' as expected.

# Current Behavior

See the attached image

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. unzip the download vue-now-ui-kit-pro-html-v1.0.0.zip
2. npm install
3. npm install vue-template-compiler
4. npm install popper.js
5. npm install jquery
6. npm run build
7. serve -s dist/
8. browse to http://localhost:5000/#/presentation
9. see the gradient block instead of the text with gradient

I have also served the dist directory from Tomcat, so it is not a 'serve' issue.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: MacBook Pro 2016
* Operating System: MacOS
* Browser and Version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
also tried in Safari - same behaviour

## Failure Logs

No issues on console

Please include any relevant log snippets or files here.
![image](https://user-images.githubusercontent.com/44422/44067212-b188516a-9fb7-11e8-9205-617930eb3216.png)

**Comment by cristijora** [comment]
Hello @adampwells  We updated the kit to v1.0.1 which includes a fix for this and also added `vue-template-compiler` + some dependency updates. Simply download the latest version from the website and it should be fine now.
