### ISSUE TITLE
Front-end and dashboard CSS conflict

### ISSUE THREAD

**Issue by Luazzo** [creativetimofficial/ct-vue-now-ui-kit-pro#12]
For the dashboard I took vue-material-dashboard free. 
But after its installation the front appearance is changed. 
Do you have any advice how to do it right.
Thank you.

**Comment by rarestoma** [comment]
Hi @Luazzo,

Thank you for working with our products and sorry for the late response.

If you are using vue-material-dashboard, please open this issue to its official repo https://github.com/creativetimofficial/vue-material-dashboard/issues so I can help you with all the details.

Thank you,
Rares
