### ISSUE TITLE
[Bug] Carousel Does not work correctly

### ISSUE THREAD

**Issue by Jahor** [creativetimofficial/ct-vue-now-ui-kit-pro#13]
### Version
1.1.1
### Reproduction link
https://www.creative-tim.com/downloads
### Operating System
MacOS 10.15.5
### Device
MBP
### Browser & Version
Safari 13.1.1, Chrome 83
### Steps to reproduce
1. Download Vue.js version of Vue Now UI Kit PRO from the website
2. unzip
3. npm install (node version 14.5.0)
4. npm serve
5. Go To http://localhost:8080/#/product
### What is expected?
Product Photos scrolling as shown on the demo website
### What is actually happening?
All Photos are shown at the same time staggered and scrolling.
Right/Left buttons don't have styles

---

**Comment by rarestoma** [comment]
Hi @Jahor,

Thank you for working with our products.

Unfortunately, the vue version of now ui kit pro doesn't have the product photos scrolling: https://demos.creative-tim.com/vue-now-ui-kit-pro.

I hope it helps.

Thank you,
Rares

**Comment by Jahor** [comment]
But it has it here:

https://demos.creative-tim.com/vue-now-ui-kit-pro/#/product

Egor Leonenko

**Comment by rarestoma** [comment]
Hi @Jahor,

I verified on the wrong page the first time. I tested https://demos.creative-tim.com/vue-now-ui-kit-pro/#/product
and it seems to work fine on the localhost. Can you please send me a short video to show me what is happening?

Thank you,
Rares

**Comment by Jahor** [comment]
https://www.dropbox.com/s/hmuvgq9ps3ebutb/brokencarousel.mov?dl=0

Egor Leonenko

**Comment by sam0910** [comment]
Exactly same issue happen to me.

**Comment by Izra-sudo** [comment]
I have the same problem with the carousel, it does not work the same as in the demo

**Comment by rarestoma** [comment]
Hi @Izra-sudo,

Please add the following css code in `src/assets/sass/now-ui-kit/_carousel.scss`:

`.el-carousel{position:relative}.el-carousel--horizontal{overflow-x:hidden}.el-carousel--vertical{overflow-y:hidden}.el-carousel__container{position:relative;height:300px}.el-carousel__arrow{border:none;outline:0;padding:0;margin:0;height:36px;width:36px;cursor:pointer;-webkit-transition:.3s;transition:.3s;border-radius:50%;background-color:rgba(31,45,61,.11);color:#FFF;position:absolute;top:50%;z-index:10;-webkit-transform:translateY(-50%);transform:translateY(-50%);text-align:center;font-size:12px}.el-carousel__arrow--left{left:16px}.el-carousel__arrow--right{right:16px}.el-carousel__arrow:hover{background-color:rgba(31,45,61,.23)}.el-carousel__arrow i{cursor:pointer}.el-carousel__indicators{position:absolute;list-style:none;margin:0;padding:0;z-index:2}.el-carousel__indicators--horizontal{bottom:0;left:50%;-webkit-transform:translateX(-50%);transform:translateX(-50%)}.el-carousel__indicators--vertical{right:0;top:50%;-webkit-transform:translateY(-50%);transform:translateY(-50%)}.el-carousel__indicators--outside{bottom:26px;text-align:center;position:static;-webkit-transform:none;transform:none}.el-carousel__indicators--outside .el-carousel__indicator:hover button{opacity:.64}.el-carousel__indicators--outside button{background-color:#C0C4CC;opacity:.24}.el-carousel__indicators--labels{left:0;right:0;-webkit-transform:none;transform:none;text-align:center}.el-carousel__indicators--labels .el-carousel__button{height:auto;width:auto;padding:2px 18px;font-size:12px}.el-carousel__indicators--labels .el-carousel__indicator{padding:6px 4px}.el-carousel__indicator{background-color:transparent;cursor:pointer}.el-carousel__indicator:hover button{opacity:.72}.el-carousel__indicator--horizontal{display:inline-block;padding:12px 4px}.el-carousel__indicator--vertical{padding:4px 12px}.el-carousel__indicator--vertical .el-carousel__button{width:2px;height:15px}.el-carousel__indicator.is-active button{opacity:1}.el-carousel__button{display:block;opacity:.48;width:30px;height:2px;background-color:#FFF;border:none;outline:0;padding:0;margin:0;cursor:pointer;-webkit-transition:.3s;transition:.3s}.carousel-arrow-left-enter,.carousel-arrow-left-leave-active{-webkit-transform:translateY(-50%) translateX(-10px);transform:translateY(-50%) translateX(-10px);opacity:0}.carousel-arrow-right-enter,.carousel-arrow-right-leave-active{-webkit-transform:translateY(-50%) translateX(10px);transform:translateY(-50%) translateX(10px);opacity:0}`

Please let me know if it works.

Thank you,
Rares

**Comment by Izra-sudo** [comment]
improved, but now the slide control of the images does it vertically and an interior slide bar appeared,
only the first image is shown
![image](https://user-images.githubusercontent.com/76443580/103014524-450c5d00-4515-11eb-84ca-b28ff8968ac5.png)

The same happens with the carousel of the product page, the image is shown but with large blank spaces and vertical sliding
![image](https://user-images.githubusercontent.com/76443580/103014865-daa7ec80-4515-11eb-9379-7b3ccdaf1a2f.png)

**Comment by insanjati** [comment]
Is this issue already fixed? Mine doesn't work properly too

**Comment by dragosct10** [comment]
Hi, @insanjati! Please try to go in the package.json and remove the ^ sign from "element-ui": "^2.13.2", then remove node_modules and package-json.lock and run the npm install again. 

Please tell us if something is changing. 

Regards,
Dragos

**Comment by insanjati** [comment]
> Hi, @insanjati! Please try to go in the package.json and remove the ^ sign from "element-ui": "^2.13.2", then remove node_modules and package-json.lock and run the npm install again.
> 
> Please tell us if something is changing.
> 
> Regards,
> Dragos

<img width="526" alt="Screen Shot 2021-04-02 at 03 42 09" src="https://user-images.githubusercontent.com/14164596/113351780-8c508800-9365-11eb-95ce-ee99c687fee9.png">

Still not working, I got the same display as https://github.com/Izra-sudo above. There's a scroll bar on its side and the image isn't placed correctly too. Please help.

**Comment by insanjati** [comment]
Hi, is there any workaround for this issue? Or maybe, could you please give me a third party plugin that is worked seamlessly with this theme?

**Comment by rarestoma** [comment]
Hi @insanjati,

Thank you for working with our products.

Can you please tell me what version of Vue Now UI Kit PRO are you using?

Thank you,
Rares

**Comment by insanjati** [comment]
Hi @rarestoma, I use the latest version: v1.1.1
