### ISSUE TITLE
[Bug] customized select doesn't look the same as demo in local

### ISSUE THREAD

**Issue by smiletrl** [creativetimofficial/ct-vue-now-ui-kit-pro#15]
### Version
1.1.1
### Reproduction link
https://digitalyl-jiazheng-dev-static.oss-cn-shanghai.aliyuncs.com/Screen%20Shot%202020-09-30%20at%209.53.52%20AM.png
### Operating System
IOS Catalina version 10.15.6
### Device
mac
### Browser & Version
Google chrome -- Version 85.0.4183.121 (Official Build) (64-bit)
### Steps to reproduce
1. npm install
2. npm run serve
3. open `http://localhost:8080/#/components`
### What is expected?
`Customizable Select` at http://localhost:8080/#/components page to be the same as demo.
### What is actually happening?
this select looks weird in local. You may download the image at  https://digitalyl-jiazheng-dev-static.oss-cn-shanghai.aliyuncs.com/Screen%20Shot%202020-09-30%20at%209.53.52%20AM.png

---

**Comment by rarestoma** [comment]
Hi @smiletrl,

Thank you for working with our products and for pointing us this issue.

Please update the css with the following code:

```
.el-select-dropdown__list{
    padding: 6px 0;
    margin: 0;
}

.el-select-dropdown__item {
    font-size: 14px;
    padding: 0 20px;
    position: relative;
    overflow: hidden;
    text-overflow: ellipsis;
    color: #606266;
    height: 34px;
    line-height: 34px;
    box-sizing: border-box;
    cursor: pointer;
}

.el-select-dropdown__item.hover, .el-select-dropdown__item:hover {
    background-color: #f5f7fa;
}
```
Please let me know if it works now.

Thank you,
Rares

**Comment by smiletrl** [comment]
hey rarestoma,

Thanks for the reply :) So I added the code into `src/components/Dropdown.vue`, and get much better result. It still doesn't look good as the demo effect though

<img width="1382" alt="Screen Shot 2020-09-30 at 8 39 41 PM" src="https://user-images.githubusercontent.com/2764799/94686378-53efd300-035d-11eb-889a-cbe2d61da2e3.png">

**Comment by smiletrl** [comment]
The multiple select is also not matching. See screen.
<img width="1439" alt="Screen Shot 2020-09-30 at 8 47 11 PM" src="https://user-images.githubusercontent.com/2764799/94687072-471faf00-035e-11eb-89ce-08ca8e739a23.png">
