### ISSUE TITLE
[Bug] The button component doesn't emit click events

### ISSUE THREAD

**Issue by skawaii** [creativetimofficial/ct-vue-now-ui-kit-pro#16]
### Version
1.1.1
### Reproduction link
http://notneeded.com
### Operating System
Linux
### Device
Laptop
### Browser & Version
Chrome 93.0.4577.82
### Steps to reproduce
1. Use the button component in a page
2. Try to listen for a `click` event.
### What is expected?
A `click` event is emitted
### What is actually happening?
Nothing.

---
### Solution
Update the button component in the PRO version to be the same as its counterpart in the FREE version.
### Additional comments
It's not everyday I find something in the free version of something that isn't included in the paid version. +)

**Comment by dragosct10** [comment]
Hi, @skawaii! Thanks for using our products. Yes, you are right! I've fixed the issue and I will deploy on live with an updated version of product. 

Regards,
Dragos

**Comment by skawaii** [comment]
Awesome, thanks!
