### ISSUE TITLE
NuxtJS integration 

### ISSUE THREAD

**Issue by pinalbhatt** [creativetimofficial/ct-vue-now-ui-kit-pro#3]
Hi - do  you have template or guidelines on how to integrate  Vue Now UI Kit Pro with  NuxtJS

**Comment by chiester** [comment]
+1

**Comment by cristijora** [comment]
Hey guys thanks for your interest in Nuxt.js. We are considering having Nuxt.js versions of some Vue.js templates but didn't decide on the approach yet. It may be possible that we will have them as separate templates but in that case people who bought Vue Now UI Kit PRO will get access to them.

**Comment by jvvlimme** [comment]
+1

**Comment by romainframe** [comment]
I don't know if it is following any Nuxt.js or Now UI Kit best practice, but I integrated the template easily inside my Nuxt project using the plugins.

Importing the plugin in the nuxt.config.js:

```javascript
export default {
  mode: 'universal',
  plugins: [
    {src: '~/plugins/bootstrap-vue', ssr: true},
    {src: '~/plugins/now-ui-kit', ssr: true},
    ...
  ],
}
```

The now-ui-kit plugin is defined as follows in my case:

```javascript
import '@/assets/sass/now-ui-kit.scss';
import globalDirectives from './globalDirectives';
import globalMixins from './globalMixins';
import globalComponents from './globalComponents';

export default {
    install(Vue) {
        Vue.use(globalDirectives);
        Vue.use(globalMixins);
        Vue.use(globalComponents);
    }
}
```

Hope it helps! And open to have feedback if things could be improved

**Comment by RudreshNarwal** [comment]
+1

**Comment by CodeWithKyrian** [comment]
import the plugin just like above
use this for the now-ui-kit.js located in the plugin folder

```
import Vue from 'vue';
import 'bootstrap/dist/css/bootstrap.css';
import '@/assets/scss/now-ui-kit.scss';
import '@/assets/demo/demo.css';
import globalDirectives from './globalDirectives';
import globalMixins from './globalMixins';
import globalComponents from './globalComponents';
import lang from 'element-ui/lib/locale/lang/en';
import locale from 'element-ui/lib/locale';

locale.use(lang);

Vue.use(globalDirectives);
Vue.use(globalMixins);
Vue.use(globalComponents);
```

go into the globalDirectivess, globalMixins and globalComponents and be sure to install all dependencies. Then go to layouts/default.vue and inport the header and footer . Worked for me
