### ISSUE TITLE
Is it support IE11? 

### ISSUE THREAD

**Issue by sam0910** [creativetimofficial/ct-vue-now-ui-kit-pro#5]
I've purchased Pro version,
Download it and build, but it is not support IE11 on windows 10.
Other browser is OK.

here is the sample build url,
http://template.labiot.co.kr/

Thanks,

**Comment by cristijora** [comment]
Hey @sam0910 
We recently did an update to the template (v1.1.0) and fixed issues related to IE support.
You can re-download the template from your "Downloads" section under your account.
Also for a quick fix you can adjust your `.babelrc` file to this version https://raw.githubusercontent.com/creativetimofficial/vue-now-ui-kit-pro/live-demo/.babelrc?token=APN0ZQQhDbhn_eyN92d9ww7TwMSH9f0_ks5caokCwA%3D%3D
