### ISSUE TITLE
Error in /now-ui-kit.scss

### ISSUE THREAD

**Issue by LaravDev** [creativetimofficial/ct-vue-now-ui-kit-pro#7]
# Prerequisites 
 
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

It should compile with run dev

# Current Behavior

shows an error compiling

# Failure Information (for bugs)
<img width="1166" alt="screen shot 2019-02-05 at 2 05 55 am" src="https://user-images.githubusercontent.com/35145882/52260269-2550f900-28eb-11e9-9329-32e3db59b79e.png">

**Comment by cristijora** [comment]
Thanks for posting the issue @LaravDev 
We did an update (v1.1.0) and fixed this problem.
You can re-download the template from "Downloads" section under your account.
